version = 1

[[annotations]]
path = [
    ".gitignore",
    ".releaserc.json",
    "LICENSE",
    "uv.lock",
    "pyproject.toml",
    "test/br.nq",
    "test/br.nt",
    "test/br_small.nq",
]
SPDX-FileCopyrightText = "2023-2026 Arcangelo Massari <arcangelo.massari@unibo.it>"
SPDX-License-Identifier = "CC0-1.0"
